// frontend/src/components/settings/NyaSelect.tsx
/*
 * NyaSelect —— 对应 Avalonia ComboBox（shadcn Select 内核）。
 * options: [{ value, label }]；value 受控，onValueChange/onChange 回调，
 * 与 Vue 版 modelValue/change 语义一致。
 */
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'

export interface NyaSelectOption { value: string; label: string }

export interface NyaSelectProps {
  value?: string
  options?: NyaSelectOption[]
  disabled?: boolean
  onValueChange?: (v: string) => void
  onChange?: (v: string) => void
}

export default function NyaSelect({ value = '', options = [], disabled = false, onValueChange, onChange }: NyaSelectProps) {
  const currentLabel = options.find((o) => o.value === value)?.label ?? ''
  return (
    <Select
      value={value || undefined}
      disabled={disabled}
      onValueChange={(v) => { onValueChange?.(v); onChange?.(v) }}
    >
      <SelectTrigger className="w-full max-w-[320px]">
        <SelectValue placeholder={currentLabel} />
      </SelectTrigger>
      <SelectContent>
        {options.map((opt) => (
          <SelectItem key={opt.value} value={opt.value}>{opt.label}</SelectItem>
        ))}
      </SelectContent>
    </Select>
  )
}

// frontend-vue-backup/src/components/settings/NyaSelect.vue
<template>
  <Select
    :model-value="modelValue"
    :disabled="disabled"
    @update:model-value="onChange"
  >
    <SelectTrigger class="w-full max-w-[320px]">
      <SelectValue :placeholder="currentLabel" />
    </SelectTrigger>
    <SelectContent>
      <SelectItem v-for="opt in options" :key="opt.value" :value="opt.value">
        {{ opt.label }}
      </SelectItem>
    </SelectContent>
  </Select>
</template>

<script setup>
/*
 * NyaSelect —— 对应 Avalonia ComboBox。内部实现换装为 shadcn Select
 * （reka-ui SelectRoot，弹层自带 .nya-pop 进出场与 bg-accent 选中弱底）。
 * options: [{ value, label }]；v-model 绑定选中 value。
 * 对外 props/emits 接口保持不变：modelValue / options / disabled → update:modelValue / change。
 */
import { computed } from 'vue';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

const props = defineProps({
  modelValue: { type: [String, Number], default: '' },
  options: { type: Array, default: () => [] },
  disabled: { type: Boolean, default: false },
});
const emit = defineEmits(['update:modelValue', 'change']);

const currentLabel = computed(() =>
  props.options.find((o) => o.value === props.modelValue)?.label ?? '');

function onChange(v) {
  emit('update:modelValue', v);
  emit('change', v);
}
</script>
